name: publish github pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_API_docs:
    runs-on: ubuntu-latest
    steps:
      - name: check working dir
        run: pwd
      - name: Render template
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: template/template.mustache
          vars: data.json
          output-file: template/index.html
          engine: mustache
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: template
