name: publish github pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_index_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Render template
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: template/template.mustache
          vars: data.json
          output-file: template/index.html
          engine: mustache
      - name: Render preview
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: template/preview.mustache
          vars: data.json
          output-file: template/preview.html
          engine: mustache
      - name: Render preview
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: template/post.mustache
          vars: data.json
          output-file: template/post.html
          engine: mustache
      - name: Install pageres
        run: npm install --global pageres-cli
      - name: create social media preview
        run: "pageres template/preview.html 1024x1024 --filename='template/preview' --overwrite"
      - name: take screenshot
        run: "pageres template/post.html 1065x780 --filename='template/screenshot' --overwrite"
      - name: copy data json to publish
        run: cp data.json template/data.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: template
          cname: meet.pcworms.ir
