name: publish github pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_API_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Render template
        # You may pin to the exact commit or the version.
        # uses: recih/template-render-action@e9d7eeb6cbcb45411b658bd7a5fe96f8eb253bca
        uses: recih/template-render-action@v1.0.2
        with:
          # Input template file path. You must specify either a template file or a template string.
          template-file: 'template/template.mustache'
          glob: 'data.json'
          output-file: 'template/index.html'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: template
