name: publish github pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create_index_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Render template
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: template/template.mustache
          vars: data.json
          output-file: template/index.html
          engine: mustache
      - name: Install pageres
        run: npm install --global pageres-cli
      - name: create social media preview
        run: pageres template/index.html 800x800 --filename='template/preview' --hide='#counter' --overwrite
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: template
